### ISSUE TITLE
TODO 1st release

### ISSUE THREAD

**Issue by miquelbeltran** [MindscapeHQ/raygun4node-aws-lambda#1]
- [x] Release Raygun4Node 1.1.0
- [x] Update references to Raygun4Node
- [x] Uncomment breadcrumbs code
- [x] General code review and testing (by the whole team)
- [x] Create npmjs package
- [x] Publish 0.0.1

**Comment by paul-uz** [comment]
@miquelbeltran whats the realistic ETA in getting this published?

I appreciate I can clone the repo and link it locally, which I still plan on doing, but an official release on NPM is ideal.

**Comment by sumitramanga** [comment]
Hi @paul-uz 

We really appreciate the eagerness - It's great to see someone looking forward to this!

We're working as quickly as possible to get this to V0.0.1 stage. PWe are also working on other high priority projects in parallel :) I've been reviewing the code and testing to speed things up. I can let you know when this is ready and when other progress has been made to the release.

Cheers,
Sumitra

**Comment by paul-uz** [comment]
Hi @sumitramanga - any update on getting this released? Eager to get working on implementing this into our own SDK

**Comment by sumitramanga** [comment]
Hi @paul-uz I'm making my way on the QA stage for the release! So far have code reviewed the AWS Lambda package we have. But I need to test this in AWS (the team finally gave me access!). So I'll pick that up soon today. I've been working in parallel with other high priority projects in the company as well. :) Thanks so much for holding on!!

**Comment by sumitramanga** [comment]
Hi @paul-uz my colleague and I are happy with release 1.1.0 going through so we've approved that. @miquelbeltran can now move onto releasing it and moving onto the next tasks on this list :) Will keep a close eye on this on my end to ensure availability of code reviewing and testing

**Comment by sumitramanga** [comment]
Hi @paul-uz Miguel has kindly released V1.1.0 of the raygun4node package and has made progress on the next steps 🙌🏽 I'll see what he needs help with regarding the comment  "General code review and testing (by the whole team)". I see some new commits pushed up in this repo so I'll take a look into those

**Comment by miquelbeltran** [comment]
0.0.1 is now available: https://www.npmjs.com/package/@raygun.io/aws-lambda
